// Autogenerated from Pigeon (v4.2.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import <Foundation/Foundation.h>
@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

@class FaceImage;

@interface FaceImage : NSObject
+ (instancetype)makeWithEncodedImage:(nullable NSArray<FlutterStandardTypedData *> *)encodedImage
    imageWidth:(nullable NSNumber *)imageWidth
    imageHeight:(nullable NSNumber *)imageHeight
    left:(nullable NSNumber *)left
    top:(nullable NSNumber *)top
    faceWidth:(nullable NSNumber *)faceWidth
    faceHeight:(nullable NSNumber *)faceHeight
    rotX:(nullable NSNumber *)rotX
    rotY:(nullable NSNumber *)rotY;
@property(nonatomic, strong, nullable) NSArray<FlutterStandardTypedData *> * encodedImage;
@property(nonatomic, strong, nullable) NSNumber * imageWidth;
@property(nonatomic, strong, nullable) NSNumber * imageHeight;
@property(nonatomic, strong, nullable) NSNumber * left;
@property(nonatomic, strong, nullable) NSNumber * top;
@property(nonatomic, strong, nullable) NSNumber * faceWidth;
@property(nonatomic, strong, nullable) NSNumber * faceHeight;
@property(nonatomic, strong, nullable) NSNumber * rotX;
@property(nonatomic, strong, nullable) NSNumber * rotY;
@end

///The codec used by FaceImageApi.
NSObject<FlutterMessageCodec> *FaceImageApiGetCodec(void);

@protocol FaceImageApi
/// @return `nil` only when `error != nil`.
- (nullable NSDictionary<NSString *, id> *)processImageFaceImage:(FaceImage *)faceImage error:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void FaceImageApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<FaceImageApi> *_Nullable api);

NS_ASSUME_NONNULL_END
