// Autogenerated from Pigeon (v4.2.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import
import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

class FaceImage {
  FaceImage({
    this.encodedImage,
    this.imageWidth,
    this.imageHeight,
    this.left,
    this.top,
    this.faceWidth,
    this.faceHeight,
    this.rotX,
    this.rotY,
  });

  List<Uint8List?>? encodedImage;
  int? imageWidth;
  int? imageHeight;
  int? left;
  int? top;
  int? faceWidth;
  int? faceHeight;
  double? rotX;
  double? rotY;

  Object encode() {
    final Map<Object?, Object?> pigeonMap = <Object?, Object?>{};
    pigeonMap['encodedImage'] = encodedImage;
    pigeonMap['imageWidth'] = imageWidth;
    pigeonMap['imageHeight'] = imageHeight;
    pigeonMap['left'] = left;
    pigeonMap['top'] = top;
    pigeonMap['faceWidth'] = faceWidth;
    pigeonMap['faceHeight'] = faceHeight;
    pigeonMap['rotX'] = rotX;
    pigeonMap['rotY'] = rotY;
    return pigeonMap;
  }

  static FaceImage decode(Object message) {
    final Map<Object?, Object?> pigeonMap = message as Map<Object?, Object?>;
    return FaceImage(
      encodedImage: (pigeonMap['encodedImage'] as List<Object?>?)?.cast<Uint8List?>(),
      imageWidth: pigeonMap['imageWidth'] as int?,
      imageHeight: pigeonMap['imageHeight'] as int?,
      left: pigeonMap['left'] as int?,
      top: pigeonMap['top'] as int?,
      faceWidth: pigeonMap['faceWidth'] as int?,
      faceHeight: pigeonMap['faceHeight'] as int?,
      rotX: pigeonMap['rotX'] as double?,
      rotY: pigeonMap['rotY'] as double?,
    );
  }
}

class _FaceImageApiCodec extends StandardMessageCodec {
  const _FaceImageApiCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is FaceImage) {
      buffer.putUint8(128);
      writeValue(buffer, value.encode());
    } else 
{
      super.writeValue(buffer, value);
    }
  }
  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 128:       
        return FaceImage.decode(readValue(buffer)!);
      
      default:      
        return super.readValueOfType(type, buffer);
      
    }
  }
}

class FaceImageApi {
  /// Constructor for [FaceImageApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  FaceImageApi({BinaryMessenger? binaryMessenger}) : _binaryMessenger = binaryMessenger;

  final BinaryMessenger? _binaryMessenger;

  static const MessageCodec<Object?> codec = _FaceImageApiCodec();

  Future<Map<String?, Object?>> processImage(FaceImage arg_faceImage) async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.FaceImageApi.processImage', codec, binaryMessenger: _binaryMessenger);
    final Map<Object?, Object?>? replyMap =
        await channel.send(<Object?>[arg_faceImage]) as Map<Object?, Object?>?;
    if (replyMap == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyMap['error'] != null) {
      final Map<Object?, Object?> error = (replyMap['error'] as Map<Object?, Object?>?)!;
      throw PlatformException(
        code: (error['code'] as String?)!,
        message: error['message'] as String?,
        details: error['details'],
      );
    } else if (replyMap['result'] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (replyMap['result'] as Map<Object?, Object?>?)!.cast<String?, Object?>();
    }
  }
}
